### PR TITLE
Fix path for CocoaPods 0.38.x

### PR DESCRIPTION
**Pull request by avdyushin**
This will fix errors on CocoaPods 0.38.x versions

### CODE REVIEW

**Comment by aharren** [comment]
Many thanks!
Arne

**Comment by avdyushin** [comment]
Can you bump version and make tag for fixed version to use it in `LibComponentLogging-pods` pod?
Thanks

**Comment by aharren** [comment]
sorry, missed that

https://github.com/aharren/LibComponentLogging-configure/commit/8ab26faafc7010fdf63eed35d5ae9569fcf89c75 - 0.1.3
https://github.com/aharren/LibComponentLogging-pods/commit/a267cb7eab2772e70998887f39fbc2c0573ece2a - 0.0.3

**Comment by avdyushin** [comment]
Thank you!

**Pull request merged**
